theme = "jellybeans"

[editor]
line-number = "relative"
mouse = false
color-modes = true
true-color = true
undercurl = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
